version: "3.1"
services:
  
  db:
    image: mysql
    container_name: mydb
    volumes:
      - /docker-entrypoint-initdb.d
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/my_password
    ports:
      - '3306:3306'
    secrets:
        - my_password

  web:
      image: qq92314/aaatest:aaa
      # volumes:
      #   - api-data:/docker_api
      ports:
        - "8000:8000"
      networks:
        - backend
      depends_on:
        - db
      deploy:
        replicas: 5
        update_config:
          parallelism: 2
        restart_policy:
          condition: on-failure
      secrets:
        - my_password

  scerets:
     my_password:
         external: true